---
- hosts: all
  become: true
  tasks:
  - name: Update repositories
    apt:
      update_cache: yes

  - name: Install apache2
    apt:
      name: apache2
      state: installed

  - name: Update apache2.conf
    template:
      src: "templates/apache2.conf"
      dest: "/etc/apache2/apache2.conf"
      owner: root
      group: root
      mode: 0644
